spring:
  datasource:
    url: jdbc:postgresql://localhost:2345/generic
    driverClassName: org.postgresql.Driver
    username: user
    password: "pass"
    hikari:
      pool-name: Hikari
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 10
      datasource-properties:
        includeSynonyms: false
  jpa:
    database: POSTGRESQL
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate # validate | create | create-drop | update | none
    properties:
      hibernate:
        synonyms: false
        format_sql: true
        show_sql: true
        default_schema: generic # or set the search_path in the database for the user
        generate_statistics: false
        enable_lazy_load_no_trans: true
        id:
          optimizer:
            pooled:
              preferred: none
  session:
    store-type: jdbc
    jdbc:
      initializer:
        enabled: true
      table-name: SPRING_SESSION
      initialize-schema: never